# Generated by Django 6.0.5 on 2026-05-17 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='joblisting',
            name='bps_grade',
            field=models.CharField(blank=True, default='', help_text='e.g., BPS-14, BPS-16', max_length=50),
        ),
        migrations.AddField(
            model_name='joblisting',
            name='location',
            field=models.CharField(blank=True, default='', help_text='e.g., Punjab, Federal, Sindh', max_length=200),
        ),
    ]
