# Generated by Django 6.0.5 on 2026-05-19 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_joblisting_bps_grade_joblisting_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mcq',
            name='option_d',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
    ]
