# Generated by Django 6.0.5 on 2026-05-19 16:48

import django.db.models.deletion
from django.db import migrations, models
from django.utils.text import slugify


def _populate_pastpaper_slugs(apps, schema_editor):
    PastPaper = apps.get_model('core', 'PastPaper')
    seen = set()
    for paper in PastPaper.objects.all():
        base = slugify(paper.title)[:300] or f'paper-{paper.pk}'
        slug = base
        counter = 1
        while slug in seen:
            slug = f'{base}-{counter}'
            counter += 1
        seen.add(slug)
        paper.slug = slug
        paper.save(update_fields=['slug'])


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_option_d_optional'),
    ]

    operations = [
        migrations.AddField(
            model_name='mcq',
            name='past_paper',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mcqs', to='core.pastpaper'),
        ),
        migrations.AddField(
            model_name='mcq',
            name='source_url',
            field=models.URLField(blank=True, default='', max_length=500),
        ),
        migrations.AddField(
            model_name='pastpaper',
            name='slug',
            field=models.SlugField(blank=True, default='', max_length=350, db_index=False),
        ),
        migrations.RunPython(_populate_pastpaper_slugs, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='pastpaper',
            name='slug',
            field=models.SlugField(blank=True, default='', max_length=350, unique=True),
        ),
        migrations.AddField(
            model_name='pastpaper',
            name='source_url',
            field=models.URLField(blank=True, default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='pastpaper',
            name='pdf_file',
            field=models.FileField(blank=True, null=True, upload_to='past_papers/'),
        ),
        migrations.AlterField(
            model_name='pastpaper',
            name='year',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
