# Generated by Django 6.0.5 on 2026-05-21 18:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_contact_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='joblisting',
            name='syllabus',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='jobs', to='core.syllabus'),
        ),
    ]
