# Generated by Django 6.0.5 on 2026-06-02 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_mcq_current_affairs_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(help_text='Announcement message or quick-link label.', max_length=255)),
                ('url', models.CharField(blank=True, default='', help_text='Optional link. Leave blank for a non-clickable message.', max_length=500)),
                ('placement', models.CharField(choices=[('headline', 'Headline (left message)'), ('link', 'Quick link (right side)')], default='headline', max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['sort_order', '-created_at'],
            },
        ),
    ]
