# Generated by Django 6.0.5 on 2026-06-02 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_announcement'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='description',
            field=models.CharField(blank=True, default='', help_text='Full name shown under the badge, e.g. Punjab Public Service Commission', max_length=255),
        ),
        migrations.AddField(
            model_name='exam',
            name='icon',
            field=models.CharField(choices=[('landmark', 'Landmark'), ('flag', 'Flag'), ('award', 'Award'), ('crown', 'Crown'), ('building', 'Building'), ('shield', 'Shield'), ('file', 'File'), ('book', 'Book')], default='landmark', help_text='Icon shown on the exam card.', max_length=20),
        ),
        migrations.AlterField(
            model_name='exam',
            name='badge_color',
            field=models.CharField(choices=[('green', 'Green'), ('blue', 'Blue'), ('amber', 'Amber'), ('red', 'Red'), ('rose', 'Rose'), ('violet', 'Violet'), ('cyan', 'Cyan'), ('slate', 'Slate')], default='green', help_text='Accent color for the exam card.', max_length=10),
        ),
    ]
