# Generated by Django 6.0.5 on 2026-06-02 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_seed_exam_meta'),
    ]

    operations = [
        migrations.AddField(
            model_name='joblisting',
            name='age_limit',
            field=models.CharField(blank=True, default='', help_text='e.g., 18-25 years (plus 5 years relaxation)', max_length=100),
        ),
        migrations.AddField(
            model_name='joblisting',
            name='experience',
            field=models.CharField(blank=True, default='', help_text='e.g., Fresh candidates can apply', max_length=200),
        ),
        migrations.AddField(
            model_name='joblisting',
            name='how_to_apply',
            field=models.JSONField(blank=True, default=list, help_text='List of how-to-apply steps (one per line in admin)'),
        ),
        migrations.AddField(
            model_name='joblisting',
            name='responsibilities',
            field=models.JSONField(blank=True, default=list, help_text='List of key responsibilities (one per line in admin)'),
        ),
        migrations.AddField(
            model_name='joblisting',
            name='salary_range',
            field=models.CharField(blank=True, default='', help_text='e.g., Rs. 22,000 - 65,000/month', max_length=200),
        ),
        migrations.AddField(
            model_name='joblisting',
            name='vacancies',
            field=models.PositiveIntegerField(default=1, help_text='Number of open positions'),
        ),
    ]
