# Generated by Django 6.0.5 on 2026-06-03 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_add_job_listing_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='badge_color',
            field=models.CharField(choices=[('green', 'Green'), ('blue', 'Blue'), ('amber', 'Amber'), ('red', 'Red'), ('rose', 'Rose'), ('violet', 'Violet'), ('cyan', 'Cyan'), ('slate', 'Slate')], default='green', help_text='Accent color for the subject card.', max_length=10),
        ),
        migrations.AddField(
            model_name='subject',
            name='icon',
            field=models.CharField(choices=[('landmark', 'Landmark'), ('flag', 'Flag'), ('award', 'Award'), ('crown', 'Crown'), ('building', 'Building'), ('shield', 'Shield'), ('file', 'File'), ('book', 'Book')], default='landmark', help_text='Icon shown on the subject card.', max_length=20),
        ),
    ]
