# Generated by Django 6.0.5 on 2026-06-03 17:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def populate_syllabus_slugs(apps, schema_editor):
    Syllabus = apps.get_model('core', 'Syllabus')
    from django.utils.text import slugify
    seen = set()
    for s in Syllabus.objects.all():
        base = slugify(f"{s.title}-{s.post_name}" if s.post_name else s.title)[:350]
        if not base:
            base = f"syllabus-{s.id}"
        slug = base
        counter = 1
        while slug in seen or Syllabus.objects.filter(slug=slug).exclude(pk=s.pk).exists():
            slug = f"{base}-{counter}"
            counter += 1
        seen.add(slug)
        s.slug = slug
        s.save(update_fields=['slug'])


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_subject_badge_color_subject_icon'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        # Step 1: add slug without unique constraint so existing rows can coexist
        migrations.AddField(
            model_name='syllabus',
            name='slug',
            field=models.SlugField(blank=True, default='', max_length=350),
        ),
        # Step 2: populate unique slugs for existing rows
        migrations.RunPython(populate_syllabus_slugs, migrations.RunPython.noop),
        # Step 3: enforce uniqueness now that all rows have distinct slugs
        migrations.AlterField(
            model_name='syllabus',
            name='slug',
            field=models.SlugField(blank=True, default='', max_length=350, unique=True),
        ),
        migrations.AlterField(
            model_name='joblisting',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('closed', 'Closed'), ('upcoming', 'Upcoming')], db_index=True, default='active', max_length=10),
        ),
        migrations.AlterField(
            model_name='mcq',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('flagged', 'Flagged')], db_index=True, default='draft', max_length=10),
        ),
        migrations.AlterField(
            model_name='mcq',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='mcqs', to='core.subject'),
        ),
        migrations.AlterField(
            model_name='pastpaper',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], db_index=True, default='draft', max_length=10),
        ),
        migrations.AlterField(
            model_name='pastpaper',
            name='subject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='past_papers', to='core.subject'),
        ),
        migrations.AddIndex(
            model_name='mcq',
            index=models.Index(fields=['exam', 'subject', 'status'], name='core_mcq_exam_id_8a3b3a_idx'),
        ),
    ]
