# Generated by Django 6.0.5 on 2026-06-03 17:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_subject_badge_color_subject_icon'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='syllabus',
            name='slug',
            field=models.SlugField(blank=True, default='', max_length=350, unique=True),
        ),
        migrations.AlterField(
            model_name='joblisting',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('closed', 'Closed'), ('upcoming', 'Upcoming')], db_index=True, default='active', max_length=10),
        ),
        migrations.AlterField(
            model_name='mcq',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('flagged', 'Flagged')], db_index=True, default='draft', max_length=10),
        ),
        migrations.AlterField(
            model_name='mcq',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='mcqs', to='core.subject'),
        ),
        migrations.AlterField(
            model_name='pastpaper',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], db_index=True, default='draft', max_length=10),
        ),
        migrations.AlterField(
            model_name='pastpaper',
            name='subject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='past_papers', to='core.subject'),
        ),
        migrations.AddIndex(
            model_name='mcq',
            index=models.Index(fields=['exam', 'subject', 'status'], name='core_mcq_exam_id_8a3b3a_idx'),
        ),
    ]
