# Generated by Django 6.0.5 on 2026-06-06 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_syllabus_marks_time_bps_grade'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='logo_url',
            field=models.URLField(blank=True, default='', help_text='External logo image URL (e.g. from scraped site or CDN).', max_length=500),
        ),
        migrations.AddField(
            model_name='subject',
            name='logo_url',
            field=models.URLField(blank=True, default='', help_text='External logo image URL (e.g. from scraped site or CDN).', max_length=500),
        ),
    ]
