# Generated by Django 6.0.5 on 2026-06-11 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_exam_logo_url_subject_logo_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='google_id',
            field=models.CharField(blank=True, db_index=True, default='', max_length=255),
        ),
    ]
