# Generated by Django 6.0.5 on 2026-06-11 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_student_google_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='google_picture',
            field=models.URLField(blank=True, default='', max_length=500),
        ),
    ]
