# Generated by Django 6.0.5 on 2026-06-12 06:19

import ckeditor_uploader.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_emailsubscription_bookmark'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Achievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=60, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=200)),
                ('icon', models.CharField(default='award', help_text='lucide icon name', max_length=30)),
                ('xp_reward', models.PositiveIntegerField(default=0)),
                ('condition_type', models.CharField(choices=[('tests_completed', 'Tests Completed'), ('streak_days', 'Streak Days'), ('mcqs_answered', 'MCQs Answered'), ('perfect_score', 'Perfect Score'), ('ppsc_tests', 'PPSC Tests'), ('night_owl', 'Night Owl'), ('login_days', 'Login Days')], default='tests_completed', max_length=30)),
                ('condition_value', models.PositiveIntegerField(default=1)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(max_length=120, unique=True)),
                ('type', models.CharField(choices=[('news', 'News'), ('blog', 'Blog')], default='blog', max_length=10)),
                ('color', models.CharField(default='#10B981', help_text='Hex color code', max_length=7)),
                ('icon', models.CharField(blank=True, default='', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('slug', models.SlugField(max_length=70, unique=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='student',
            name='daily_goal',
            field=models.PositiveIntegerField(default=20, help_text='Daily MCQ target'),
        ),
        migrations.AddField(
            model_name='student',
            name='daily_test_goal',
            field=models.PositiveIntegerField(default=1, help_text='Daily test target'),
        ),
        migrations.AddField(
            model_name='student',
            name='last_practice_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='level',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='student',
            name='mcqs_today',
            field=models.PositiveIntegerField(default=0, help_text='MCQs answered today'),
        ),
        migrations.AddField(
            model_name='student',
            name='notify_affairs',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='student',
            name='notify_jobs',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='student',
            name='notify_papers',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='student',
            name='reminder_time',
            field=models.TimeField(blank=True, help_text='Daily reminder time', null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='streak_days',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='student',
            name='target_exam',
            field=models.CharField(blank=True, choices=[('', 'None'), ('PPSC', 'PPSC'), ('FPSC', 'FPSC'), ('CSS', 'CSS'), ('NTS', 'NTS'), ('PMS', 'PMS')], default='', max_length=20),
        ),
        migrations.AddField(
            model_name='student',
            name='tests_today',
            field=models.PositiveIntegerField(default=0, help_text='Tests completed today'),
        ),
        migrations.AddField(
            model_name='student',
            name='xp_points',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('past_paper', 'New Past Paper'), ('job_posted', 'New Job Posted'), ('current_affairs', 'Current Affairs Ready'), ('streak_reminder', 'Streak Reminder'), ('achievement', 'Achievement Unlocked'), ('system', 'System')], default='system', max_length=20)),
                ('message', models.CharField(max_length=300)),
                ('link', models.CharField(blank=True, default='', max_length=200)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=250, unique=True)),
                ('content', ckeditor_uploader.fields.RichTextUploadingField()),
                ('excerpt', models.TextField(blank=True, default='', help_text='Short summary')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='posts/thumbnails/')),
                ('post_type', models.CharField(choices=[('news', 'News'), ('blog', 'Blog')], default='blog', max_length=10)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], default='draft', max_length=15)),
                ('is_featured', models.BooleanField(default=False)),
                ('views_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to=settings.AUTH_USER_MODEL)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='core.category')),
                ('tags', models.ManyToManyField(blank=True, related_name='posts', to='core.tag')),
            ],
            options={
                'ordering': ['-published_at', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PostImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='posts/images/')),
                ('caption', models.CharField(blank=True, default='', max_length=200)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='core.post')),
            ],
            options={
                'verbose_name': 'Post Image',
                'verbose_name_plural': 'Post Images',
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='TestAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_id', models.PositiveIntegerField()),
                ('question_text', models.TextField()),
                ('option_a', models.TextField(blank=True, default='')),
                ('option_b', models.TextField(blank=True, default='')),
                ('option_c', models.TextField(blank=True, default='')),
                ('option_d', models.TextField(blank=True, default='')),
                ('correct_option', models.CharField(max_length=1)),
                ('selected_option', models.CharField(blank=True, default='', max_length=1)),
                ('explanation', models.TextField(blank=True, default='')),
                ('is_correct', models.BooleanField(default=False)),
                ('test_result', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='core.testresult')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='DailyPracticeLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('mcqs_answered', models.PositiveIntegerField(default=0)),
                ('tests_completed', models.PositiveIntegerField(default=0)),
                ('xp_earned', models.PositiveIntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='practice_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date'],
                'unique_together': {('user', 'date')},
            },
        ),
        migrations.CreateModel(
            name='UserAchievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unlocked_at', models.DateTimeField(auto_now_add=True)),
                ('achievement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.achievement')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='achievements', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'achievement')},
            },
        ),
    ]
