# Generated by Django 6.0.5 on 2026-06-12 10:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_chatsession_chatmessage_aiusage_newssubscriber'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ServicePlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, help_text='Price in PKR', max_digits=10)),
                ('applications_included', models.PositiveIntegerField(help_text='Number of applications included')),
                ('validity_days', models.PositiveIntegerField(blank=True, help_text='Days of validity (null for monthly)', null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['price'],
            },
        ),
        migrations.AddField(
            model_name='joblisting',
            name='domicile_requirement',
            field=models.CharField(blank=True, choices=[('punjab', 'Punjab'), ('sindh', 'Sindh'), ('kpk', 'Khyber Pakhtunkhwa'), ('balochistan', 'Balochistan'), ('ict', 'Islamabad (ICT)'), ('gilgit', 'Gilgit-Baltistan'), ('ajk', 'Azad Jammu & Kashmir')], default='', help_text='Domicile requirement (leave blank for any)', max_length=20),
        ),
        migrations.AddField(
            model_name='joblisting',
            name='gender_requirement',
            field=models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female')], default='', help_text='Gender requirement (leave blank for both)', max_length=10),
        ),
        migrations.AddField(
            model_name='joblisting',
            name='max_age',
            field=models.PositiveIntegerField(blank=True, help_text='Maximum age in years', null=True),
        ),
        migrations.AddField(
            model_name='joblisting',
            name='min_age',
            field=models.PositiveIntegerField(blank=True, help_text='Minimum age in years', null=True),
        ),
        migrations.AddField(
            model_name='joblisting',
            name='min_education',
            field=models.CharField(blank=True, choices=[('matric', 'Matric'), ('intermediate', 'Intermediate'), ('graduation', 'Graduation'), ('masters', 'Masters'), ('mphil', 'MPhil'), ('phd', 'PhD')], default='', help_text='Minimum education level required', max_length=20),
        ),
        migrations.AddField(
            model_name='joblisting',
            name='min_experience_years',
            field=models.PositiveIntegerField(blank=True, help_text='Minimum years of experience (0 for fresh)', null=True),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('past_paper', 'New Past Paper'), ('job_posted', 'New Job Posted'), ('current_affairs', 'Current Affairs Ready'), ('streak_reminder', 'Streak Reminder'), ('achievement', 'Achievement Unlocked'), ('job_match', 'Job Match Found'), ('service_request', 'Service Request Update'), ('system', 'System')], default='system', max_length=20),
        ),
        migrations.CreateModel(
            name='ApplicationRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_snapshot', models.JSONField(blank=True, default=dict, help_text='Snapshot of user profile at request time')),
                ('special_instructions', models.TextField(blank=True, default='', help_text='User notes for the submission')),
                ('payment_status', models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('refunded', 'Refunded')], default='pending', max_length=10)),
                ('payment_method', models.CharField(blank=True, choices=[('jazzcash', 'JazzCash'), ('easypaisa', 'EasyPaisa'), ('bank_transfer', 'Bank Transfer'), ('manual', 'Manual')], default='', max_length=20)),
                ('payment_reference', models.CharField(blank=True, default='', help_text='Transaction ID / reference number', max_length=100)),
                ('payment_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('payment_screenshot', models.ImageField(blank=True, help_text='Payment proof screenshot', null=True, upload_to='service_payments/')),
                ('request_status', models.CharField(choices=[('payment_pending', 'Payment Pending'), ('payment_verification', 'Payment Verification'), ('queued', 'Queued'), ('in_progress', 'In Progress'), ('submitted', 'Submitted'), ('failed', 'Failed'), ('refunded', 'Refunded')], default='payment_pending', max_length=20)),
                ('submission_screenshot', models.ImageField(blank=True, help_text='Proof of submission', null=True, upload_to='service_submissions/')),
                ('submission_reference', models.CharField(blank=True, default='', help_text='Application number after submission', max_length=100)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('failure_reason', models.TextField(blank=True, default='', help_text='Reason if submission failed')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_requests', to=settings.AUTH_USER_MODEL)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_requests', to='core.joblisting')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='application_requests', to=settings.AUTH_USER_MODEL)),
                ('plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='requests', to='core.serviceplan')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AdminNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('added_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admin_notes_added', to=settings.AUTH_USER_MODEL)),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admin_notes', to='core.applicationrequest')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_type', models.CharField(choices=[('cnic_front', 'CNIC Front'), ('cnic_back', 'CNIC Back'), ('domicile', 'Domicile Certificate'), ('character', 'Character Certificate'), ('other', 'Other')], max_length=20)),
                ('file', models.FileField(upload_to='job_profiles/documents/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_documents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='UserEducation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(choices=[('matric', 'Matric'), ('intermediate', 'Intermediate'), ('graduation', 'Graduation'), ('masters', 'Masters'), ('mphil', 'MPhil'), ('phd', 'PhD')], max_length=20)),
                ('board_university', models.CharField(blank=True, default='', max_length=200)),
                ('passing_year', models.PositiveIntegerField(blank=True, null=True)),
                ('total_marks', models.PositiveIntegerField(blank=True, null=True)),
                ('obtained_marks', models.PositiveIntegerField(blank=True, null=True)),
                ('grade', models.CharField(blank=True, default='', max_length=20)),
                ('certificate_file', models.FileField(blank=True, null=True, upload_to='job_profiles/education/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='educations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-level', '-passing_year'],
            },
        ),
        migrations.CreateModel(
            name='UserExperience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organization', models.CharField(max_length=200)),
                ('designation', models.CharField(max_length=200)),
                ('from_date', models.DateField()),
                ('to_date', models.DateField(blank=True, null=True)),
                ('is_current', models.BooleanField(default=False)),
                ('experience_letter', models.FileField(blank=True, null=True, upload_to='job_profiles/experience/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='experiences', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-from_date'],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(blank=True, default='', max_length=200)),
                ('father_name', models.CharField(blank=True, default='', max_length=200)),
                ('cnic', models.CharField(blank=True, default='', help_text='Encrypted CNIC number', max_length=50)),
                ('dob', models.DateField(blank=True, null=True)),
                ('domicile', models.CharField(blank=True, choices=[('punjab', 'Punjab'), ('sindh', 'Sindh'), ('kpk', 'Khyber Pakhtunkhwa'), ('balochistan', 'Balochistan'), ('ict', 'Islamabad (ICT)'), ('gilgit', 'Gilgit-Baltistan'), ('ajk', 'Azad Jammu & Kashmir')], default='', max_length=20)),
                ('religion', models.CharField(blank=True, choices=[('islam', 'Islam'), ('christianity', 'Christianity'), ('hinduism', 'Hinduism'), ('sikhism', 'Sikhism'), ('other', 'Other')], default='', max_length=20)),
                ('gender', models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], default='', max_length=10)),
                ('permanent_address', models.TextField(blank=True, default='')),
                ('current_address', models.TextField(blank=True, default='')),
                ('phone', models.CharField(blank=True, default='', max_length=30)),
                ('whatsapp_number', models.CharField(blank=True, default='', max_length=30)),
                ('profile_photo', models.ImageField(blank=True, null=True, upload_to='job_profiles/photos/')),
                ('is_profile_complete', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='job_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='JobApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('applied_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('saved', 'Saved'), ('applied', 'Applied'), ('roll_number', 'Roll Number Received'), ('test_scheduled', 'Test Scheduled'), ('interview', 'Interview'), ('selected', 'Selected'), ('rejected', 'Rejected')], default='saved', max_length=20)),
                ('roll_number', models.CharField(blank=True, default='', max_length=100)),
                ('test_date', models.DateTimeField(blank=True, null=True)),
                ('test_venue', models.CharField(blank=True, default='', max_length=300)),
                ('notes', models.TextField(blank=True, default='')),
                ('reminder_sent', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='core.joblisting')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_applications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-applied_at'],
                'unique_together': {('user', 'job')},
            },
        ),
    ]
