# Generated by Django 6.0.5 on 2026-06-19 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_ai_subscription'),
    ]

    operations = [
        migrations.AddField(
            model_name='aisubscription',
            name='payment_reference',
            field=models.CharField(blank=True, default='', help_text='Transaction ID / reference number', max_length=100),
        ),
        migrations.AddField(
            model_name='aisubscription',
            name='payment_screenshot',
            field=models.ImageField(blank=True, help_text='Payment proof screenshot', null=True, upload_to='ai_payments/'),
        ),
    ]
