# Generated by Django 6.0.5 on 2026-06-20 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_tag_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='icon',
            field=models.CharField(choices=[('landmark', 'Landmark'), ('globe', 'Globe / World'), ('flag', 'Flag'), ('map-pin', 'Map Pin'), ('mountain', 'Mountain'), ('book', 'Book'), ('book-open', 'Book Open'), ('library', 'Library'), ('graduation-cap', 'Graduation'), ('pen-tool', 'Pen Tool'), ('feather', 'Feather'), ('alphabet', 'Alphabet'), ('languages', 'Languages'), ('calculator', 'Calculator'), ('chart-bar', 'Chart Bar'), ('triangle', 'Triangle'), ('square-root', 'Square Root'), ('binary', 'Binary / CS'), ('laptop', 'Laptop'), ('code', 'Code'), ('flask', 'Flask'), ('atom', 'Atom'), ('dna', 'DNA'), ('microscope', 'Microscope'), ('rocket', 'Rocket'), ('sun', 'Sun'), ('cloud', 'Cloud'), ('zap', 'Zap / Energy'), ('brain', 'Brain'), ('lightbulb', 'Lightbulb'), ('scale', 'Scale / Law'), ('gavel', 'Gavel'), ('building', 'Building'), ('landmark-building', 'Landmark Building'), ('newspaper', 'Newspaper'), ('radio', 'Radio'), ('history', 'History'), ('clock', 'Clock'), ('calendar', 'Calendar'), ('users', 'Users'), ('user', 'User'), ('heart-pulse', 'Health'), ('leaf', 'Environment'), ('coins', 'Economics'), ('trending-up', 'Trending Up'), ('shield', 'Shield'), ('star', 'Star'), ('moon', 'Moon'), ('compass', 'Compass')], default='book', help_text='Icon shown on the subject card.', max_length=20),
        ),
    ]
